name: Hello

on:
  workflow_dispatch:


jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to user
        run: echo "Hello Ali"
  
      - name: say hello username
        run: echo "Hello $USER"


  details:
    runs-on: ubuntu-latest
    steps:
      - name: check docker version
        run: docker --version

      
