name: tmkc

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to me
        run: echo "hello $USER"

      - name: say hello to developer
        run: echo "hello Dev"

  bye:
    runs-on: ubuntu-latest
    steps:
      - name: check docker version
        run: docker --version

        



      
