name: hello

on:
    workflow_dispatch:
#   push:
#     branches: [main]

jobs: 
  checkfile: 
    runs-on: ubuntu-latest

    steps:
      - name: say hello to user
        uses: actions/checkout@v4

      - name: checkout code
        run: |
          if [ -f index.html ]; then
            echo "index.html file is found in the repository"
          else
            echo "index.html file is not found in the repository"
            exit 1
          fi