name: multi-stage

on: 
    workflow_dispatch:

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps: 
            - name: code checkout
              uses: actions/checkout@v4

            - name: show current files
              run: ls -a

            - name: success Message 
              run: echo pipeline executed successfully
            